version: '3.7'

services:

    office1:
        image: postgres:10
        restart: always
        environment:
            POSTGRES_PASSWORD: s1
        networks:
            uni_network:
                  ipv4_address: 172.20.20.2
        ports:
             - 6666:5432
        volumes:
             - ./sql/:/docker-entrypoint-initdb.d
            

    office2:
        image: postgres:10
        restart: always
        environment:
            POSTGRES_PASSWORD: s2
        networks:
            uni_network:
                  ipv4_address: 172.20.20.3
        ports:
             - 7777:5432
        volumes:
             - ./sql/:/docker-entrypoint-initdb.d

    bucardo:
        image: plgr/bucardo
        volumes:
               - ./config/:/media/bucardo
        depends_on:
               - office1
               - office2
        networks:
            uni_network:
                  ipv4_address: 172.20.20.5


networks:
  uni_network:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.20.20.0/24
